### ISSUE TITLE
404 GET https://geo-gecko.github.io/3W_20170822_1651/data/UgandaDistricts.unhighlighted.geojson

### ISSUE THREAD

**Issue by benjaminug** [Geo-Gecko/3W_20170822_1651#1]
I noticed this 404. You removed the rest of the districts with out data. There is still a reference to this geojson file.

![3w map - uganda - google chrome 2017-09-08 10 04 35](https://user-images.githubusercontent.com/1018969/30199925-85106ffa-947d-11e7-888e-fe373a7efeca.png)

**Comment by Dizux** [comment]
Comment out the d3.defer element that calls the districts.
should be fixed, if I may ask which IDE is that?
