### ISSUE TITLE
Indentation bug

### ISSUE THREAD

**Issue by Dizux** [Geo-Gecko/3W_20170822_1651#2]
![image](https://user-images.githubusercontent.com/22677548/30210014-4c97a000-94a3-11e7-9bd4-6e42e80a285c.png)
On inital load, it looks fine, but when selecting anything changes to this
![capture2](https://user-images.githubusercontent.com/22677548/30210083-a5759f6a-94a3-11e7-8aba-2e1f673af25a.PNG)

And "Clear all" wont fix it

**Comment by benjaminug** [comment]
Its because at this stage, Protection is empty, so it doesnt show. What you can do is make sure the Protection contains the total of everything under it in the CSV or implement it programatically. 

In the meantime, the fix i made was to remove the indentation if Protection is missing.

**Comment by benjaminug** [comment]
But i made a temporary fix. I disable the click event on Protection since it doesnt have any data as of now.
